### ISSUE TITLE
Allo Boss Dac

### ISSUE THREAD

**Issue by hvddrift** [odinb/bash-plexamp-installer#10]
Hi

I have a Pi with a Allo Boss Dac hat (https://allo.com/sparky/boss-dac.html)

Have you ever come across one of these? It worked with Volmio but I am unsure what settings to do to have it work with plexamp.

Any help would be appreciated.

Thanks in Advance,

**Comment by odinb** [comment]
Hi!

Will have to add this to the script.

Never worked/played with these cards myself, but should be straight forward!

Just have some patience, and I will add it. Give me a day or 2.

//Odin

**Comment by odinb** [comment]
Added option for allo Boss HIFI DAC and variants.

Section "--== Fix allo setup ==--" is added.

//Odin

**Comment by hvddrift** [comment]
Thank you.... Works perfectly
