### ISSUE TITLE
plexamp not playing (not sure this is related to installation or plexamp)

### ISSUE THREAD

**Issue by APMOadmin** [odinb/bash-plexamp-installer#14]
+++ posted the same question to Plex(amp) forum +++

Am having the same original issue - plexamp my not playing anything
Environment:

Raspberry Pi 400
RaspberryOS 64bit with GUI, all updates applied
Plexamp 4.6.1 installed via [GitHub - odinb/bash-plexamp-installer: PlexAmp-installer for Raspberry Pi with ARM64 HW. Headless music-player controlled from any other Plexamp client.](https://github.com/odinb/bash-plexamp-installer)
plexamp user: ‘plexamp’, GUI user ‘administrator’
client Chromium/localhost, Safari/iOS, Chrome/iOS, Safari/MacOS, Crome/MacOS, Chrome/Linux, Firefox/Ubuntu (I think we can rule out a client related issue)
==> and yes clients are casting to correct plexamp instance (image attached)
Audio Library - Plex Server in local network, in remote network or Tidal (again I think we can rule out audio source/format related issues)
PlexWeb client plays fine on same machine
Audio device: default, default audio device, USB audio out, HDMI out, pulse audio, or any other device with sample rate matching on or off
Log attached…
Any hint of what is wrong or where to look for is most appreciated

[Plexamp.log](https://github.com/odinb/bash-plexamp-installer/files/10535735/Plexamp.log)
![IMG_3713](https://user-images.githubusercontent.com/15325226/215477093-75942690-16da-47b2-83c0-7f4de2cc5753.PNG)

**Comment by odinb** [comment]
Hi!

From your log, I can see that you are not properly logged in (403 Forbidden, 404 Not Found):
Jan 29, 2023 20:49:58.932 [Javascript] INFO - ViewState: Error loading from storage. Unexpected token u in JSON at position 0
Jan 29, 2023 20:49:59.015 [Javascript] INFO - METRICS: Error loading from storage. Unexpected token u in JSON at position 0Jan 29, 2023 20:49:59.198 [Javascript] WARNING - DEVICE: Error loading cloud players from plex.tv HTTP status 403
Jan 29, 2023 20:49:59.262 [Javascript] INFO - Cloud: [SharedItems] Error getting data: HTTP status 404
Jan 29, 2023 20:50:09.155 [Javascript] INFO - Cloud: [SharedItems] Error getting data: HTTP status 404
