### ISSUE TITLE
Cosmetic request - script should update the motd banner logo on subsequent releases

### ISSUE THREAD

**Issue by doasfan** [odinb/bash-plexamp-installer#15]
Hello,
My /etc/update-motd.d/20-logo displays the ASCII logo and "Plexamp-Linux-headless-v4.5.3" on ssh login. I've been hoping it would be replaced with an updated logo/banner/message of the day displaying the correct corresponding version, but I've done several upgrades and each version since has not updated the logo file.

Would be nice to have the logo updated with the correct version.

Thanks!

![Capture](https://user-images.githubusercontent.com/9890160/216781208-cd735165-33f0-471e-8ace-d4534c53d708.JPG)

**Comment by odinb** [comment]
Well, it actually does update, at least on all of mine!
This is currently line 281 of the script! (line number will change in future versions)

![Screenshot 2023-02-04 at 13 07 27](https://user-images.githubusercontent.com/11250708/216785257-2551c7cf-4f02-4a74-b4d9-058331d55eba.png)

What OS are you running (output using `cat /etc/os-release`)?

What do you see if you run the following 2 lines at command-line (no changes committed):
`PLEXAMPV="Plexamp-Linux-headless-v4.6.2"`
`sed -e "s#Plexamp-Linux-.*#"$PLEXAMPV\""#g" /etc/update-motd.d/20-logo`

You should get the motd with correct version, if not, let me know what you get!

**Comment by odinb** [comment]
Since I have not heard back, I will close.
