### ISSUE TITLE
Getting a "Couldn't start playback" error in the web interface

### ISSUE THREAD

**Issue by rkcerman** [odinb/bash-plexamp-installer#18]
Hi,

Using this setup:

Raspberry Pi 4 Model B Rev 1.4
HiFiBerry Digi+ Pro

I am using this set up for Roon/ropieee on a different SD card and it works.
Freshly installed on a fresh memory card, tried the complete install twice, still same results.

I manage to launch the web interface successfully, but upon selection of songs I get "Couldn't start playback"

Here is my aplay -l:

> pi@plexamp:~ $ aplay -l
> **** List of PLAYBACK Hardware Devices ****
> card 0: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> card 1: E30 [E30], device 0: USB Audio [USB Audio]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> card 2: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> card 3: sndrpihifiberry [snd_rpi_hifiberry_digi], device 0: HiFiBerry Digi+ Pro HiFi wm8804-spdif-0 [HiFiBerry Digi+ Pro HiFi wm8804-spdif-0]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0

During installation I choose the option "Digi/Digi+" (is it good enough for Digi+ pro as well?)
Let me know what logs I should attach because I cannot find anything useful anywhere

In web interface settings in Audio -> Playback I have selected the Hifiberry card, but still no success, even after reboot.

Help please?

**Comment by odinb** [comment]
Hi!

As you can see from: https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/
You need to have:
DIGI+
dtoverlay=hifiberry-digi

DIGI+ PRO
dtoverlay=hifiberry-digi-pro

So from the script his would be option 4 "setup for Digi2 Pro":
    1 ) echo "You picked $opt, continue with 6 or choose again!"; HIFIBERRY="dtoverlay=hifiberry-dacplus";;
    2 ) echo "You picked $opt, continue with 6 or choose again!"; HIFIBERRY="dtoverlay=hifiberry-dac";;
    3 ) echo "You picked $opt, continue with 6 or choose again!"; HIFIBERRY="dtoverlay=hifiberry-digi";;
    4 ) echo "You picked $opt, continue with 6 or choose again!"; HIFIBERRY="dtoverlay=hifiberry-digi-pro";;
    5 ) echo "You picked $opt, continue with 6 or choose again!"; HIFIBERRY="dtoverlay=hifiberry-amp";;

So, re-run the script, and change only your card. Then reboot. If it still does not work, try pulling power for 10 seconds.
After this it should work if you see In web interface, settings in Audio -> Playback and the Hifiberry card is selected. If not selected, then re-select it!

After this it should work.
