### ISSUE TITLE
Support for multi device streaming with SnapJack

### ISSUE THREAD

**Issue by RAYs3T** [odinb/bash-plexamp-installer#20]
Hey,

with the "original" installer, we also provision snapjack to enable multi-room / multi-device streaming.

This would be a great addition for this installer.

See: https://github.com/elan/snapjack-installer/blob/main/installer.sh

**Comment by odinb** [comment]
That URL gives me a 404, can you please provide a functional link?

**Comment by RAYs3T** [comment]
https://gist.github.com/RAYs3T/b1e0e07e5d3572459c06afbd8ffd8bbc

**Comment by odinb** [comment]
What version of Plexamp will this work for? Plexamp-Linux-headless-v4.8.x and newer?
Looking into this now...

**Comment by RAYs3T** [comment]
Good question, it's supported for at least the last 6 months, maybe even longer. Not sure what exact version.
I were using the beta releases, but this has already made it into the release.

**Comment by odinb** [comment]
Hi Kevin! Should be added successfully to the script now! Hopefully it works as intended. How does one activate multi-room audio after it has been enabled? Not much I can find on this on the web...

**Comment by RAYs3T** [comment]
Hey @odinb awesome - I can test it today as I have 2 PIs set up with it.
As far as I know it detects if SnapJack is preset and if there are multiple devices in the network.

**Comment by elan** [comment]
Totally unreleased and unsupported. Don't make us feature flag it until release 😆

**Comment by odinb** [comment]
> Totally unreleased and unsupported. Don't make us feature flag it until release 😆

Is it enough to have a disclaimer (see script), or you want me to fully remove?
Also, is it done correctly, os I am prepared for later when released?

**Comment by elan** [comment]
Please remove until we release.

**Comment by odinb** [comment]
Ok, done! Was the script correct install-wise otherwise for SnapJack?

**Comment by elan** [comment]
SnapJack will have its own installer; from the outside in, so to speak.
