### ISSUE TITLE
Flags on the command?

### ISSUE THREAD

**Issue by JohnGalt1717** [odinb/bash-plexamp-installer#25]
I'd love to be able to use this fully scripted.  Is it possible to add all of the options as flags to the command line and have it automatically pass them in and just go?

**Comment by odinb** [comment]
There are several ways to do this, the 2 I can think of are:
1) To script, you can send:
echo "Y Y N N Y N Y Y N" | ./the_script
This allow you to pass any sequence of "Y" or "N" to the script.

2) Another option is to use automation tools, like "expect" or "ansible":
https://linux.die.net/man/1/expect
https://docs.ansible.com/ansible/latest/getting_started/index.html
Have used both, and use Ansible most of the time these days!

Just keep in mind that the order of Y/N responses can change over time as the script evolves and adds/removes options.
