### ISSUE TITLE
audio setup now needs to sed to /boot/firmware/config.txt

### ISSUE THREAD

**Issue by ghost** [odinb/bash-plexamp-installer#27]
With the latest version of RaspberryPi OS /boot/config.txt isn't accessible anymore it is now at /boot/firmware/config.txt

**Comment by odinb** [comment]
Hi ItsVRK!

Thanks for the contribution! I see the change here: https://www.raspberrypi.com/documentation/computers/config_txt.html
This also means the script will no longer be backwards compatible with 11 (bullseye), and forward will only support 12 (bookworm).

**Comment by odinb** [comment]
Ok, updated revision notes, and the README.

**Comment by newelement** [comment]
Hmm I feel like this should have queried for the version id. 11 = bullseye, 12 = bookworm. Then made the adjustments based on that.

**Comment by newelement** [comment]
`. /etc/os-release`
`echo "$VERSION_ID"`

OR

`lsb_release -sr`

**Comment by odinb** [comment]
Well, since Bullseye is end-of-life later this year, probably within the next 1-2 months, I did not feel it was worth the effort!
https://wiki.debian.org/DebianReleases#Current_Releases.2FRepositories

Also, re-installing on Bookworm is fairly quick, and very straight-forward.
