### ISSUE TITLE
incorrect directory name

### ISSUE THREAD

**Issue by pscharfg** [odinb/bash-plexamp-installer#3]
Hi and thanks for putting this together.

Line 367 of your script needs to be updated from:

`sed -i "s#WorkingDirectory=/home/pi/plexamp#WorkingDirectory=/home/"$USER"/plexamp#g" /home/brodersen/.config/systemd/user/plexamp.service`

to
`sed -i "s#WorkingDirectory=/home/pi/plexamp#WorkingDirectory=/home/"$USER"/plexamp#g" /home/"$USER"/.config/systemd/user/plexamp.service`

**Comment by odinb** [comment]
Thanks for reporting, do appreciate it! You are absolutely correct! Updated now!
