### ISSUE TITLE
Installer doesn't create systemctl files on DietPi

### ISSUE THREAD

**Issue by dlasher** [odinb/bash-plexamp-installer#6]
First, thank you for creating this installer, fantastic work!

Second, I have an army of dietpi machines, and I ran the installer on a couple tonight. Plexamp can be started by hand (node js/index.js) and when you do, it works just fine. However, the installer didn't create any of the systemD files needed to set it to start on boot.

I'll go digging through the script, but hoping you can provide them as stand-alone in the short term, and add support tin the installer as a fix?

thank you!

**Comment by odinb** [comment]
Will have a look. Might take a couple of days, as I am quite busy with other things, and DietPi is best effort, since I do not run it myself.

**Comment by dlasher** [comment]
Fair enough, thank you @odinb for the quick response. 

based on getting it running, it appears to need a couple of things:
1. correct user/group/working directory
2. enable as root, rather than --user


Here's what I ended up with:

[Unit]
Description=Plexamp
After=network-online.target
Requires=network-online.target

[Service]
Type=simple
User=dietpi
Group=dietpi
WorkingDirectory=/home/dietpi/plexamp
ExecStart=/usr/bin/node /home/dietpi/plexamp/js/index.js
Restart=on-failure

[Install]
WantedBy=basic.target

**Comment by odinb** [comment]
Hi! Should work now, please remove your manually installed/configured unit-file for the service, and re-run the installer!
Basically you run it as an upgrade, and it should fix the unit-file etc. without wiping existing tokens etc.
Let me know any findings.
