### ISSUE TITLE
node install on ubuntu jammy based systems

### ISSUE THREAD

**Issue by tgp-2** [odinb/bash-plexamp-installer#8]
Hello, just a heads up ... it seems the nodesource repo for node 12 is not supported on ubuntu jammy based systems. Jammy main repo still has node 12, so adding this as a fallback installer option might be useful. NVM is another option, but adding this might require more significant changes to the installer.

**Comment by odinb** [comment]
Hi!

This installer is for a headless Plexamp running on RPi-hardware, so your Ubuntu-situation is not really an intended target of this project!

However, in order to be flexible, I added a switch for the Node.v12 install-part, making it optional!

Hope this works for you!

**Comment by tgp-2** [comment]
Thanks for the reply ... just to clarify, this would be for a headless install :)
With the raspberry pi supply shortage, many are looking for alternative devices ... in my case, I have an odroid-c4 and a nanopi-r4s ... both run ubuntu/armbian jammy (minimal/headless, not a full desktop), and both are great for Plexamp
So for this scenario, one could first install nodejs from the main repo, then run your installer and choose the option to skip node install ... think I got it, thanks!

    On Sunday, September 18, 2022 at 02:45:09 PM PDT, odinb ***@***.***> wrote:  
 
 


Hi!

This installer is for a headless Plexamp running on RPi-hardware, so your Ubuntu-situation is not really an intended target of this project!

However, in order to be flexible, I added a switch for the Node.v12 install-part, making it optional!

Hope this works for you!

**Comment by odinb** [comment]
Correct, just skip the Node.v12 part.
Do not have the Odroid-C4 myself, but I do have a couple of the Odroid N2+ (Running CoreElec on one, and Homeassisitant on the other).

Seems Armbian is available, assuming it is similar to Raspbian, so not Ubuntu.
https://www.armbian.com/odroid-c4/

**Comment by tgp-2** [comment]
yep, I tried Armbian for the C4 ... I also have a HiFiShield+ i2s DAC HAT, and unfortunately the custom kernel module only works with the vendor supplied version of Ubuntu (so I couldn't get it to work with Armbian)
    On Sunday, September 18, 2022 at 03:27:40 PM PDT, odinb ***@***.***> wrote:  
 
 


Do not have the Odroid-C4 myself, but I do have a couple of the Odroid N2+ (Running CoreElec on one, and Homeassisitant on the other).

Seems Armbian is available, assuming it is similar to Raspbian, so not Ubuntu.
https://www.armbian.com/odroid-c4/
